# web __APP_NAME__ config.
#  server {
#         listen 80;
#         listen [::]:80;
#         server_name __APP_NAME____ENVIRONMENT__.internal-apps.buff.com;
#         return 301 https://$host$request_uri;
# }

server {
        #listen 443;
        listen 80;
        server_name __APP_NAME____ENVIRONMENT__.internal-apps.buff.com;
        #include wildcard.conf;

       
        location / {
            proxy_redirect off;
            proxy_pass http://__APP_NAME__-app-1:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $remote_addr;
        }
}